### ISSUE TITLE
Nav-bar doesn't highlight current page.

### ISSUE THREAD

**Issue by gardeneda** [gardeneda/2800-202310-BBY21#7]
Currently do not have time to figure this logic out, as I need to get working on the chat interface.

If anyone finds time in the future, please work on this bit.

**Comment by RanP90** [comment]
Implementation is done and merged to dev. Current page will be displayed in bold in nav-bar

**Comment by gardeneda** [comment]
Navbar highlighting on Profile is jank and Exercise page.
